import Head from "next/head";
import Banner from "../components/Banner";
import MediumCard from "../components/MediumCard";
import Header from "../components/Header";
import SmallCard from "../components/SmallCard";
import LargCard from "../components/LargCard";
import Footer from "../components/Footer";

const database_adress =
  "https://airbnb-clone-d2585-default-rtdb.europe-west1.firebasedatabase.app/";

const popularEndPoint = "popular.json";
const cardsDataEndPoint = "card_data.json";

export default function Home({ exploreData, cardsData }) {
  return (
    <div className="">
      <Head>
        <title>Zoher Air bnb</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <Banner />
      <main className="max-w-7xl mx-auto px-8 sm:px-16">
        <section className="pt-6">
          <h2 className="text-4xl font-semibold pb-5">Explore Nearby</h2>
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">
            {exploreData?.map((item, index) => {
              return (
                <SmallCard
                  key={index}
                  img={item.img}
                  location={item.location}
                  distance={item.distance}
                />
              );
            })}
          </div>
        </section>
        <section>
          <h2 className="text-4xl font-semibold py-8">Live Anywhere</h2>
          <div className="flex overflow-scroll space-x-3 scrollbar-hide p-3 -ml-3">
            {cardsData?.map((item, index) => {
              return (
                <MediumCard key={index} img={item.img} title={item.title} />
              );
            })}
          </div>
        </section>
        <LargCard
          img="https://links.papareact.com/4cj"
          title="The Greatest Outdoors"
          description="Wishlists curated by Airbnb."
          buttonText="Get Inspired"
        />
      </main>
      <Footer />
    </div>
  );
}

export async function getStaticProps() {
  const exploreData = await fetch(database_adress + popularEndPoint).then(
    (res) => res.json()
  );
  const cardsData = await fetch(database_adress + cardsDataEndPoint).then(
    (res) => res.json()
  );

  return {
    props: {
      exploreData,
      cardsData,
    },
  };
}
